#include"debug.h"

struct instruction_info {
	int length;
	char* mnemonic_format;
};

static struct instruction_info instruction_infos[256] = {
		{1, "NOP"},
		{3, "LD\tBC, 0x%04X"},
		{1, "LD\t(BC), A"},
		{1, "INC\tBC"},
		{1, "INC\tB"},
		{1, "DEC\tB"},
		{2, "LD\tB, 0%02X"},
		{1, "RLCA"},
		{3, "LD\t(0x%04X), SP"},
		{1, "ADD\tHLC, BC"},
		{1, "LD\tA, (BC)"},
		{1, "DEC\tBC"},
		{1, "INC\tC"},
		{1, "DEC\tC"},
		{2, "LD\tC, 0x%02X"},
		{1, "RRCA"},
		{2, "STOP\t0"},
		{3, "LD\tDE, 0x%04X"},
		{1, "LD\t(DE), A"},
		{1, "INC\tDE"},
		{1, "INC\tD"},
		{1, "DEC\tD"},
		{2, "LD\tD, 0x%02X"},
		{1, "RLA"},
		{2, "JR\t0x%02X"},
		{1, "ADD\tHL, DE"},
		{1, "LD\tA, (DE)"},
		{1, "DEC\tDE"},
		{1, "INC\tE"},
		{1, "DEC\tE"},
		{2, "LD\tE, 0x%02X"},
		{1, "RRA"},
		{2, "JR\tNZ, %d"},
		{3, "LD\tHL, 0x%04X"},
		{1, "LD\t(HL+), A"},
		{1, "INC\tHL"},
		{1, "INC\tH"},
		{1, "DEC\tH"},
		{2, "LD\tH, 0x%02X"},
		{1, "DAA"},
		{2, "JR\tZ, %d"},
		{1, "ADD\tHL, HL"},
		{1, "LD\tA, (HL+)"},
		{1, "DEC\tHL"},
		{1, "INC\tL"},
		{1, "DEC\tL"},
		{2, "LD\tL, 0x%02X"},
		{1, "CPL"},
		{2, "JR\tNC, %d"},
		{3, "LD\tSP, 0x%04X"},
		{1, "LD\t(HL-), A"},
		{1, "INC\tSP"},
		{1, "INC\t(HL)"},
		{1, "DEC\t(HL)"},
		{2, "LD\t(HL), 0x%02X"},
		{1, "SCF"},
		{2, "JR\tC, %d"},
		{1, "ADD\tHL, SP"},
		{1, "LD\tA, (HL-)"},
		{1, "DEC\tSP"},
		{1, "INC\tA"},
		{1, "DEC\tA"},
		{2, "LD\tA, 0x%02X"},
		{1, "CCF"},
		{1, "LD\tB, B"},
		{1, "LD\tB, C"},
		{1, "LD\tB, D"},
		{1, "LD\tB, E"},
		{1, "LD\tB, H"},
		{1, "LD\tB, L"},
		{1, "LD\tB, (HL)"},
		{1, "LD\tB, A"},
		{1, "LD\tC, B"},
		{1, "LD\tC, C"},
		{1, "LD\tC, D"},
		{1, "LD\tC, E"},
		{1, "LD\tC, H"},
		{1, "LD\tC, L"},
		{1, "LD\tC, (HL)"},
		{1, "LD\tC, A"},
		{1, "LD\tD, B"},
		{1, "LD\tD, C"},
		{1, "LD\tD, D"},
		{1, "LD\tD, E"},
		{1, "LD\tD, H"},
		{1, "LD\tD, L"},
		{1, "LD\tD, (HL)"},
		{1, "LD\tD, A"},
		{1, "LD\tE, B"},
		{1, "LD\tE, C"},
		{1, "LD\tE, D"},
		{1, "LD\tE, E"},
		{1, "LD\tE, H"},
		{1, "LD\tE, L"},
		{1, "LD\tE, (HL)"},
		{1, "LD\tE, A"},
		{1, "LD\tH, B"},
		{1, "LD\tH, C"},
		{1, "LD\tH, D"},
		{1, "LD\tH, E"},
		{1, "LD\tH, H"},
		{1, "LD\tH, L"},
		{1, "LD\tH, (HL)"},
		{1, "LD\tH, A"},
		{1, "LD\tL, B"},
		{1, "LD\tL, C"},
		{1, "LD\tL, D"},
		{1, "LD\tL, E"},
		{1, "LD\tL, H"},
		{1, "LD\tL, L"},
		{1, "LD\tL, (HL)"},
		{1, "LD\tL, A"},
		{1, "LD\t(HL), B"},
		{1, "LD\t(HL), C"},
		{1, "LD\t(HL), D"},
		{1, "LD\t(HL), E"},
		{1, "LD\t(HL), H"},
		{1, "LD\t(HL), L"},
		{1, "HALT"},
		{1, "LD\t(HL), A"},
		{1, "LD\tA, B"},
		{1, "LD\tA, C"},
		{1, "LD\tA, D"},
		{1, "LD\tA, E"},
		{1, "LD\tA, H"},
		{1, "LD\tA, L"},
		{1, "LD\tA, (HL)"},
		{1, "LD\tA, A"},
		{1, "ADD\tA, B"},
		{1, "ADD\tA, C"},
		{1, "ADD\tA, D"},
		{1, "ADD\tA, E"},
		{1, "ADD\tA, H"},
		{1, "ADD\tA, L"},
		{1, "ADD\tA, (HL)"},
		{1, "ADD\tA, A"},
		{1, "ADC\tA, B"},
		{1, "ADC\tA, C"},
		{1, "ADC\tA, D"},
		{1, "ADC\tA, E"},
		{1, "ADC\tA, H"},
		{1, "ADC\tA, L"},
		{1, "ADC\tA, (HL)"},
		{1, "ADC\tA, A"},
		{1, "SUB\tB"},
		{1, "SUB\tC"},
		{1, "SUB\tD"},
		{1, "SUB\tE"},
		{1, "SUB\tH"},
		{1, "SUB\tL"},
		{1, "SUB\t(HL)"},
		{1, "SUB\tA"},
		{1, "SBC\tA, B"},
		{1, "SBC\tA, C"},
		{1, "SBC\tA, D"},
		{1, "SBC\tA, E"},
		{1, "SBC\tA, H"},
		{1, "SBC\tA, L"},
		{1, "SBC\tA, (HL)"},
		{1, "SBC\tA, A"},
		{1, "AND\tB"},
		{1, "AND\tC"},
		{1, "AND\tD"},
		{1, "AND\tE"},
		{1, "AND\tH"},
		{1, "AND\tL"},
		{1, "AND\t(HL)"},
		{1, "AND\tA"},
		{1, "XOR\tB"},
		{1, "XOR\tC"},
		{1, "XOR\tD"},
		{1, "XOR\tE"},
		{1, "XOR\tH"},
		{1, "XOR\tL"},
		{1, "XOR\t(HL)"},
		{1, "XOR\tA"},
		{1, "OR\tB"},
		{1, "OR\tC"},
		{1, "OR\tD"},
		{1, "OR\tE"},
		{1, "OR\tH"},
		{1, "OR\tL"},
		{1, "OR\t(HL)"},
		{1, "OR\tA"},
		{1, "CP\tB"},
		{1, "CP\tC"},
		{1, "CP\tD"},
		{1, "CP\tE"},
		{1, "CP\tH"},
		{1, "CP\tL"},
		{1, "CP\t(HL)"},
		{1, "CP\tA"},
		{1, "RET\tNZ"},
		{1, "POP\tBC"},
		{3, "JP\tNZ, 0x%04X"},
		{3, "JP\t0x%04X"},
		{3, "CALL\tNZ, 0x%04X"},
		{1, "PUSH\tBC"},
		{2, "ADD\tA, 0x%02X"},
		{1, "RST\t0x00"},
		{1, "RET\tZ"},
		{1, "RET"},
		{3, "JP\tZ, 0x%04X"},
		{4, "CB"},
		{3, "CALL\tZ, 0x%04X"},
		{3, "CALL\t0x%04X"},
		{2, "ADC\tA, 0x%02X"},
		{1, "RST\t0x08"},
		{1, "RET\tNC"},
		{1, "POP\tDE"},
		{3, "JP\tNC, 0x%04X"},
		{1, "NIL"},
		{3, "CALL\tNC, 0x%04X"},
		{1, "PUSH\tDE"},
		{2, "SUB\t0x%02X"},
		{1, "RST\t0x10"},
		{1, "RET\tC"},
		{1, "RETI"},
		{3, "JP\tC, 0x%04X"},
		{1, "NIL"},
		{3, "CALL\tC, 0x%04X"},
		{1, "NIL"},
		{2, "SBC\tA, 0x%02X"},
		{1, "RST\t0x18"},
		{2, "LDH\t(0x%02X), A"},
		{1, "POP\tHL"},
		{2, "LD\t(C), A"},
		{1, "NIL"},
		{1, "NIL"},
		{1, "PUSH\tHL"},
		{2, "AND\t0x%02X"},
		{1, "RST\t0x20"},
		{2, "ADD\tSP, %d"},
		{1, "JP\t(HL)"},
		{3, "LD\t(0x%04X), A"},
		{1, "NIL"},
		{1, "NIL"},
		{1, "NIL"},
		{2, "XOR\t0x%02X"},
		{1, "RST\t0x28"},
		{2, "LDH\tA, (0x%02X)"},
		{1, "POP\tAF"},
		{2, "LD\tA, (C)"},
		{1, "DI"},
		{1, "NIL"},
		{1, "PUSH\tAF"},
		{2, "OR\t0x%02X"},
		{1, "RST\t0x30"},
		{2, "LD\tHL, SP + %d"},
		{1, "LD\tSP, HL"},
		{3, "LD\tA, (0x%04X)"},
		{1, "EI"},
		{1, "NIL"},
		{1, "NIL"},
		{2, "CP\t0x%02X"},
		{1, "RST\t0x38"}
};


int debug_op_length(d8 opcode)
{
	return instruction_infos[opcode].length;
}


char* debug_op_mnemonic_format(d8 opcode)
{
	return instruction_infos[opcode].mnemonic_format;
}
