name: Project build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./src
